(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['main'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper;

  return "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Site Title</title>\n    <link rel=\"stylesheet\" href=\"/style.css\">\n\n    <!-- This 3rd-party stylesheet makes available the font families to be used for this page (\"Roboto\" and \"Roboto Slab\"). -->\n    <link href=\"https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab:100\" rel=\"stylesheet\">\n\n    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.4.2/handlebars.runtime.js\" charset=\"utf-8\"></script>\n\n    <script src=\"/NoteTemplate.js\" charset=\"utf-8\" defer></script>\n    <script src=\"/ClassTemplate.js\" charset=\"utf-8\" defer></script>\n    <script src=\"/AddNoteButtonTemplate.js\" charset=\"utf-8\" defer></script>\n    <script src=\"/AddClassButtonTemplate.js\" charset=\"utf-8\" defer></script>\n\n    <script src=\"/client.js\" charset=\"utf-8\" charset=\"utf-8\" defer></script>\n\n\n  </head>\n\n  <body>\n\n    <header>\n        <h1 class=\"site-title\"><a href=\"#\">Site Title</a></h1>\n    </header>\n    <main class=\"content\">\n\n          "
    + ((stack1 = ((helper = (helper = helpers.body || (depth0 != null ? depth0.body : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : (container.nullContext || {}),{"name":"body","hash":{},"data":data,"loc":{"start":{"line":30,"column":10},"end":{"line":30,"column":20}}}) : helper))) != null ? stack1 : "")
    + "\n\n    </main>\n\n  </body>\n</html>\n";
},"useData":true});
})();